export const ACTION_TYPES = {
    FETCH_START:'FETCH_START',
    FETCH_SUCCESS:'FETCH_SUCCESS',
    FETCH_CURRENT_DATA:'FETCH_CURRENT_DATA',
    FETCH_ERROR:'FETCH_ERROR',
    FETCH_FINAL:'FETCH_FINAL'
}